require('./tests/_round');
require('./tests/_maxChar');
require('./tests/_arraySum');
require('./tests/_fizzBuzz');
require('./tests/_capitalize');
require('./tests/_objectMerge')
require('./tests/_vowelCount');
require('./tests/_arrayMerge');
require('./tests/_arrayToTree');
require('./tests/_longestWord');
require('./tests/_isPalindrome');
require('./tests/_simpleAdding');
require('./tests/_isMultipleOf');
require('./tests/_objectForEach');
require('./tests/_reverseString');
require('./tests/_firstRecurringChar');
require('./tests/_alphabeticallySort');